[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-8_x"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile || pnpm install"]

[phases.build]
cmds = ["pnpm codegen"]

[start]
cmd = "pnpm start"

[variables]
PORT = "42069"