[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-8_x"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile || pnpm install"]

[phases.build]
cmds = ["pnpm codegen"]

[start]
cmd = "sh ./start.sh"

[variables]
HOST = "0.0.0.0"
HOSTNAME = "0.0.0.0"