[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm codegen"

[deploy]
startCommand = "node simple-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"