[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm codegen"

[deploy]
startCommand = "sh ./start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"