[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm codegen"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PORT = "${{PORT}}"
HOST = "0.0.0.0"